### ISSUE TITLE
Webrtc-vad is missing

### ISSUE THREAD

**Issue by vergnu** [denoming/webrtc-vad#1]
Hello, denoming.
The webpage after the webrtc-vad link of this project is missing.  Could you help fix it again? I would greatly appreciate it! thanks!

**Comment by denoming** [comment]
Hello, I don't fully understand you. The webrtc-vad is present here: https://github.com/denoming/webrtc-vad.

**Comment by vergnu** [comment]
Hello. Firstly, I am very grateful for your response to my question. I saw your updated webpage, which is the website you posted in your response:https://github.com/denoming/webrtc-vad.  
But after the update, I still can't open this link.
![3](https://github.com/denoming/webrtc-vad/assets/157200317/699091d8-b89c-43c5-9052-e7cbea3f34da)
I used the right mouse button to open the connection in the new tab, and the interface is as follows
![f2f5cfa5b0ea5f3017ef4c5280ea6e0](https://github.com/denoming/webrtc-vad/assets/157200317/0ad39ed5-191f-46f7-9a06-09363b9c89fe) 
I am a beginner, am I not sure if this situation is normal. I really want to reproduce your esp32-i2s-mic-vad code, but I don't know how to do it.
Thanks!

**Comment by denoming** [comment]
I see. I can't do it as well. Probably this is is intended by GitHub. Anyway, this kind of link means the git submodule. Take a look to the `.gitmodules` file and you will find the direct link to the WebRTC source code: https://webrtc.googlesource.com/src and `8cc711a` means the hash code on what git should checkout to. But, you should not do it on your own and just follow instructions in README file of mentioned project, because the command `git submodule update --init --recursive` should clone all sub-modules.

**Comment by vergnu** [comment]
I understand. Thank you for your detailed answer!
